Feature/svms 4 - Footer (sem elementor)
studiovisual/hello-theme-child pull request #7
Opened 2024-12-17 11:35 UTC by dcavalheiro-sv

Desenvolvimento do novo footer da Studio Visual
https://studiovisual.atlassian.net/browse/SVMS-4

Dynamic-footer, CSS, ícones necessárias e alteração no functions.php para encontrar os caminhos.

2024-12-23 19:25 UTC, dcavalheiro-sv commented
@gsilva-sv alterei a branch.

2025-01-20 14:04 UTC, gsilva-sv requested changes

2025-01-20 14:04 UTC, gsilva-sv commented on template-parts/dynamic-footer.php
> +				$menu_items = wp_get_nav_menu_items(get_nav_menu_locations()['primary-footer-menu']);
Usar o uso padrão de menu do Wordpress.

2025-01-20 14:04 UTC, gsilva-sv commented on assets/css/sv-variables.css
> +  --color-0000: #000000;
Recomendo usar o padrão do tailwind

2025-01-20 18:38 UTC, elopes-sv commented on template-parts/dynamic-footer.php
> +			<a class="sv-footer__logo-link" href="<?php echo home_url(); ?>">
Feito

2025-01-20 18:41 UTC, elopes-sv commented on template-parts/dynamic-footer.php
> +												<li><a href="<?php echo esc_url($sub_item->url); ?>"><?php echo esc_html($sub_item->title); ?></a></li>
Não será necessário, pois utilizaremos o menu padrão do WordPress, onde podemos definir o título diretamente pelo painel admin.

2025-01-20 19:05 UTC, elopes-sv commented on template-parts/dynamic-footer.php
> +			<p>Menu de rodapé não configurado.</p>
Mensagem removida, usaremos o menu padrão WordPress.

2025-01-20 19:09 UTC, elopes-sv commented on template-parts/dynamic-footer.php
> +			<p class="sv-footer__description"><?php echo esc_html(get_bloginfo('description', 'display')); ?></p>
Neste primeiro momento, deixamos estático, pois existem outros componentes estáticos no código. Em uma versão futura, podemos pensar em tornar todos dinâmicos. Não seria aconselhável trabalhar nisso agora, pois o número de horas já ultrapassou e muito o previsto inicialmente.

2025-01-20 20:07 UTC, myamashita-sv approved these changes

2025-01-20 20:21 UTC, gsilva-sv approved these changes

2025-01-20 21:18 UTC, merged